#!/bin/bash
# This script added required repositiories for the furnish script

#Java7
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update --yes --force-yes
sudo apt-get install --yes --force-yes oracle-jdk7-installer

java -version

sudo gedit /etc/encironment

"JAVA_HOME=/usr/lib/jvm/java-7-oracle"

#HOWTO CHANGE BETWEEN JAVA VERSIONS!!? guide is gone :(
